name: VariableSleep
version: ${project.version}
main: me.raddari.variablesleep.VariableSleep
api-version: 1.14.1
authors: [Raddari]
description: ${project.description}
commands:
  variablesleep:
    description: Reloads the config file
    usage: /variablesleep reload
    aliases: [vs]